# Generated by Django 5.2.5 on 2025-08-21 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_booking_guest_remove_booking_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in digits only (8-15 digits).', regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
    ]
